<?php
/**
 * @file
 * assessment_ux.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function assessment_ux_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'addanother_button_assessment_assignment';
  $strongarm->value = 1;
  $export['addanother_button_assessment_assignment'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'addanother_message_assessment_assignment';
  $strongarm->value = 1;
  $export['addanother_message_assessment_assignment'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'addanother_tab_assessment_assignment';
  $strongarm->value = 1;
  $export['addanother_tab_assessment_assignment'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'addanother_tab_edit_assessment_assignment';
  $strongarm->value = 1;
  $export['addanother_tab_edit_assessment_assignment'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'additional_settings__active_tab_assessment_assignment';
  $strongarm->value = 'edit-wysiwyg-template';
  $export['additional_settings__active_tab_assessment_assignment'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'diff_enable_revisions_page_node_assessment_assignment';
  $strongarm->value = 0;
  $export['diff_enable_revisions_page_node_assessment_assignment'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'diff_show_preview_changes_node_assessment_assignment';
  $strongarm->value = 0;
  $export['diff_show_preview_changes_node_assessment_assignment'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'diff_view_mode_preview_node_assessment_assignment';
  $strongarm->value = 'full';
  $export['diff_view_mode_preview_node_assessment_assignment'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'field_bundle_settings_assessment_item__graded_item';
  $strongarm->value = array(
    'view_modes' => array(),
    'extra_fields' => array(
      'form' => array(),
      'display' => array(),
    ),
  );
  $export['field_bundle_settings_assessment_item__graded_item'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'jammer_author_options';
  $strongarm->value = array(
    'assessment_assignment' => 'assessment_assignment',
    'cis_course' => 'cis_course',
    'section' => 'section',
  );
  $export['jammer_author_options'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'jammer_body_options';
  $strongarm->value = array();
  $export['jammer_body_options'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'jammer_comment_settings';
  $strongarm->value = array(
    'assessment_assignment' => 'assessment_assignment',
    'cis_course' => 'cis_course',
    'section' => 'section',
  );
  $export['jammer_comment_settings'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'jammer_delete_button_unset_node_types';
  $strongarm->value = array();
  $export['jammer_delete_button_unset_node_types'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'jammer_menu_options';
  $strongarm->value = array(
    'assessment_assignment' => 'assessment_assignment',
    'cis_course' => 'cis_course',
    'section' => 'section',
  );
  $export['jammer_menu_options'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'jammer_node_promoted';
  $strongarm->value = 1;
  $export['jammer_node_promoted'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'jammer_node_sticky';
  $strongarm->value = 1;
  $export['jammer_node_sticky'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'jammer_path_options';
  $strongarm->value = array(
    'assessment_assignment' => 'assessment_assignment',
    'cis_course' => 'cis_course',
    'section' => 'section',
  );
  $export['jammer_path_options'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'jammer_preview_button_unset_node_types';
  $strongarm->value = array(
    'assessment_assignment' => 'assessment_assignment',
    'cis_course' => 'cis_course',
    'section' => 'section',
  );
  $export['jammer_preview_button_unset_node_types'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'jammer_revision_information';
  $strongarm->value = array(
    'assessment_assignment' => 'assessment_assignment',
    'cis_course' => 'cis_course',
    'section' => 'section',
  );
  $export['jammer_revision_information'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'jammer_revision_log_textarea_unset_node_types';
  $strongarm->value = array(
    'assessment_assignment' => 'assessment_assignment',
    'cis_course' => 'cis_course',
    'section' => 'section',
  );
  $export['jammer_revision_log_textarea_unset_node_types'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'jammer_submit_button_unset_node_types';
  $strongarm->value = array();
  $export['jammer_submit_button_unset_node_types'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'jammer_teaser_controls_unset_node_types';
  $strongarm->value = array(
    'assessment_assignment' => 'assessment_assignment',
    'cis_course' => 'cis_course',
    'section' => 'section',
  );
  $export['jammer_teaser_controls_unset_node_types'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'jammer_user_delete_hide_button';
  $strongarm->value = 0;
  $export['jammer_user_delete_hide_button'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'save_continue_assessment_assignment';
  $strongarm->value = 'Save and add fields';
  $export['save_continue_assessment_assignment'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'wysiwyg_template_default_assessment_assignment';
  $strongarm->value = '';
  $export['wysiwyg_template_default_assessment_assignment'] = $strongarm;

  return $export;
}
