<?php
/**
 * @file Web components integration
 */

/**
 * Implements hook_page_build().
 */
function webcomponents_page_build(&$page) {
  $components = webcomponents_load_all();
  $files = array();
  // ensure files w/ multiple elements are only
  // imported once
  foreach ($components as $component) {
    // if it matches multiple to same file
    // it doesn't matter since it'll still be available
    $files[$component->file] = $component;
  }
  // let developers modify which files are appended to the document
  // right before we do so
  drupal_alter('webcomponent_attached_files', $files);
  // write the component file reference to the screen
  foreach ($files as $component) {
    _webcomponents_add_to_head($component);
  }
  // load webcomponentsjs polyfill library if it exists
  $libraries = libraries_get_libraries();
  if (isset($libraries['webcomponents']) && is_dir(DRUPAL_ROOT . '/' . $libraries['webcomponents'] . '/webcomponentsjs')) {
    drupal_add_js(base_path() . $libraries['webcomponents'] . '/webcomponentsjs/webcomponents-lite.min.js', array('weight' => -100000, 'group' => JS_LIBRARY));
  }
}

/**
 * Implements hook_entity_info().
 */
function webcomponents_entity_info() {
  $info = array();
  $info['webcomponent'] = array(
    'label' => t('Web component'),
    'base table' => 'webcomponents',
    'entity keys' => array(
      'id' => 'wid',
      'label' => 'title',
      'bundle' => 'type',
    ),
    'uri callback' => 'webcomponent_uri',
    'module' => 'webcomponents',
    'entity class' => 'Entity',
    'controller class' => 'EntityAPIController',
    'fieldable' => FALSE,
    'bundle keys' => array(
      'bundle' => 'type',
    ),
  );
  return $info;
}

/**
 * URI callback for entity
 */
function webcomponent_uri($webcomponent) {
  return array(
    'path' => 'webcomponent/' . $webcomponent->machine_name,
  );
}

/**
 * Return output for rendering a component
 * @param  array $component fully loaded webcomponent entity.
 * @return string            rendered representation of the component
 */
function _webcomponents_render_component($component) {
  if (isset($component->properties)) {
    if (!is_array($component->properties)) {
      $component->properties = unserialize($component->properties);
    }
    _webcomponents_add_to_head($component);
    // support token replacement of properties passed in
    foreach ($component->properties as &$property) {
      $property = token_replace($property);
    }
    $vars = array(
      'tag' => $component->machine_name,
      'properties' => $component->properties,
    );
    // allow other projects to add onto and modify the webcomponent before it renders
    // useful for tag wrapping for systems like HAX
    drupal_alter('webcomponent_render', $vars, $component);
    $output = theme('webcomponent', $vars);
    return $output;
  }
  return FALSE;
}

/**
 * Implements hook_theme().
 */
function webcomponents_theme() {
  // test all components on the file system against what's
  // in the database to ensure the data models haven't changed
  _webcomponents_rebuild();
  // hilariously minor template
  return array(
    'webcomponent' => array(
      'variables' => array(
        'tag' => '',
        'properties' => array(),
        'innerHTML' => '',
        'wrap_tag' => '',
        'wrap_tag_close' => '',
      ),
      'render element' => 'element',
      'template' => 'webcomponent',
      'path' => drupal_get_path('module', 'webcomponents') . '/templates',
    ),
  );
}

/**
 * Implements hook_entity_update().
 */
function webcomponents_entity_update($entity, $type) {
  // perform check for everything that IS NOT a webcomponent since that's circular
  if ($type != 'webcomponent' && isset($entity->webcomponents_additional) && !empty($entity->webcomponents_additional)) {
    // load entity info so we can grab the generic id and revision keys
    $info = entity_get_info($type);
    // insert into this table based on the revision and all known webcomponent
    // additional field data that we've stored
    db_insert('webcomponents_content')
    ->fields(array(
      'etid' => $entity->{$info['entity keys']['id']},
      'etvid' => $entity->{$info['entity keys']['revision']},
      'etype' => $type,
      'additional_properties' => serialize($entity->webcomponents_additional),
    ))
    ->execute();
  }
}

/**
 * Implements hook_entity_load().
 */
function webcomponents_entity_load($entities, $type) {
  if ($type == 'webcomponent') {
    // unpack properties
    foreach ($entities as $entity) {
      $entity->properties = unserialize($entity->properties);
    }
  }
  // allow any other entity to utilize the built in webcomponent_content map
  else {
    // ensure table exists, goofy issue where this can happen during install
    if (db_table_exists('webcomponents_content')) {
      $info = entity_get_info($type);
      foreach ($entities as $entity) {
        $query = db_select('webcomponents_content', 'wc');
        // match entity type
        $query->condition('wc.etype', $type, '=');
        // snag this entity id
        $query->condition('wc.etid', $entity->{$info['entity keys']['id']}, '=');
        // snag this revision if it exists
        if ($info['entity keys']['revision']) {
          $query->condition('wc.etvid', $entity->{$info['entity keys']['revision']}, '=');
        }
        // return additional properties since this will have the mapping
        $query->fields('wc', array('additional_properties'));
        // execute
        $result = $query->execute();
        // Build up the array of data to add to the entity
        foreach ($result->fetchAll() as $row) {
          $entity->webcomponents_additional = unserialize($row->additional_properties);
        }
      }
    }
  }
}

/**
 * Load all webcomponents in the database.
 * @return array array of entities or empty.
 */
function webcomponents_load_all() {
  $entities = &drupal_static(__FUNCTION__);
  // @ignore druplart_conditional_assignment
  if (!$entities) {
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'webcomponent');
    $query->execute();
    $result = $query->execute();
    // flip the results if it found them
    if (isset($result['webcomponent'])) {
      $keys = array_keys($result['webcomponent']);
      $entities = entity_load('webcomponent', $keys);
    }
    else {
      $entities = array();
    }
  }
  return $entities;
}

/**
 * Rebuild webcomponents from the file system.
 */
function _webcomponents_rebuild() {
  // force rebuild of components from static
  $processed = array();
  // load all possible web components
  $componentfiles = webcomponents_load_webcomponents_files();
  // build the registry of possible component types
  $registry = _webcomponents_build_registry();
  // loop through results found, tagged by format they are in
  foreach ($componentfiles as $format => $files) {
    // process each file based on user defined callback for
    // how we've been told to handle processing of this component type
    if (!empty($files)) {
      foreach ($files as $file) {
        if (isset($registry[$format])) {
          $processed[$file] = call_user_func($registry[$format]['process'], $file);
          // ensure there was actually a match of some kind in there
          // with support for multiple element definitions per file
          if (!empty($processed[$file]) && is_array($processed[$file])) {
            foreach ($processed[$file] as $component) {
              // try and load webcomponent by machine name
              if ($entity = webcomponent_load_by_name($component->machine_name)) {
                foreach ($component as $key => $value) {
                  // see if any aspects changed
                  if ($key != 'file' && isset($entity->{$key}) && $entity->{$key} != $value) {
                    drupal_set_message(t('Web components have changed! Make sure that your attributes are correctly reflected in your site. @key changed on @machine from @old to @new', array('@key' => $key, '@old' => $entity->{$key}, '@new' => $value, '@machine' => $component->machine_name)), 'warning', TRUE);
                    $entity->{$key} = $value;
                  }
                }
                if (is_array($entity->properties)) {
                  $entity->properties = serialize($entity->properties);
                }
                entity_save('webcomponent', $entity);
              }
              else {
                // try and create the entity instead
                if (!empty($component->properties)) {
                  $component->properties = serialize($component->properties);
                }
                // ensure the file wasn't empty
                if (isset($component->machine_name)) {
                  $entity = entity_create('webcomponent', (array)$component);
                  entity_save('webcomponent', $entity);
                }
              }
            }
          }
        }
      }
    }
  }
}

/**
 * Add webcomponent to the header of the site so it can work.
 */
function _webcomponents_add_to_head($component) {
  $element = array(
    '#tag' => 'link', // The #tag is the html tag
    '#attributes' => array( // Set up an array of attributes inside the tag
      'href' => base_path() . $component->file,
      'rel' => 'import',
    ),
  );
  drupal_add_html_head($element, 'webcomponent-' . $component->machine_name);
}

/**
 * Return all available web component types registered.
 * Basically just that they have a callback so we know how
 * to process and convert them from static into database driven.
 * @return array array of possible formats and callbacks
 */
function _webcomponents_build_registry() {
  $formats = module_invoke_all('register_component_format');
  drupal_alter('register_component_format', $formats);
  return $formats;
}

/**
 * Assembles components available to Drupal.
 * @return array files where components live
 */
function webcomponents_load_webcomponents_files() {
  $componentfiles = module_invoke_all('webcomponents');
  drupal_alter('webcomponents', $components);
  return $componentfiles;
}

/**
 * Load webcomponent by name
 * @param  string $name machine name of a webcomponent
 * @return object       fully loaded entity
 */
function webcomponent_load_by_name($name) {
  $entity = entity_load('webcomponent', FALSE, array('machine_name' => $name));
  $entity = array_pop($entity);
  return $entity;
}

/**
 * Sniff out html files in a directory
 * @param  string $dir a directory to search for .html includes
 * @return array       an array of html files to look for web components in
 */
function _webcomponents_find_html_includes($dir) {
  $files = array();
  if (is_dir($dir)) {
    // step into the polymer directory and find all html templates
    $di = new DirectoryIterator(DRUPAL_ROOT . '/' . $dir);
    foreach ($di as $fileinfo) {
      $fname = $fileinfo->getFilename();
      // only include html file, not index
      if (strpos($fname, '.html') && $fname != 'index.html') {
        $files[] = $dir . $fileinfo->getFilename();
      }
      elseif (is_dir($dir . $fname) && $fname != '.' && $fname != '..') {
        $di2 = new DirectoryIterator($dir . $fname);
        foreach ($di2 as $fileinfo2) {
          $fname2 = $fileinfo2->getFilename();
          // only include html file, not index
          if (strpos($fname2, '.html') && $fname2 != 'index.html') {
            $files[] = $dir . $fname . '/' . $fname2;
          }
          elseif (is_dir($dir . $fname . '/' . $fname2) && $fname2 != '.' && $fname2 != '..') {
            $di3 = new DirectoryIterator($dir . $fname . '/' . $fname2);
            foreach ($di3 as $fileinfo3) {
              $fname3 = $fileinfo3->getFilename();
              // only include html file, not index
              if (strpos($fname3, '.html') && $fname3 != 'index.html') {
                $files[] = $dir . $fname . '/' . $fname2 . '/' . $fname3;
              }
            }
          }
        }
      }
    }
  }
  return $files;
}
