<?php
/**
 * @file
 * Code for the MOOC Helper feature.
 */

include_once 'mooc_helper.features.inc';

/**
 * Implements hook_preprocess().
 *
 * Add a class to match our view-modes
 */
function mooc_helper_preprocess(&$variables, $hook) {
  if ($hook == 'node') {
    $variables['classes_array'][] = $hook . '-view-mode-' . $variables['view_mode'];
  }
}

/**
 * Implements hook_menu_contextual_links_alter().
 */
function mooc_helper_menu_contextual_links_alter(&$links, $router_item, $root_path) {
  // Add a link to all contextual links for nodes.
  if ($root_path == 'node/%') {
    unset($links['cis_lmsless-delete']);
    $tmp = explode('/', $router_item['href']);
    $entity_id = array_pop($tmp);
    // link to print the outline
    $links['cis_lmsless_print_outline'] = array(
      'title' => t('Print'),
      'href' => 'book/export/html/' . $entity_id,
      'localized_options' => array(),
    );
    // outline below here
    $links['cis_lmsless_outline_designer'] = array(
      'title' => t('Outline'),
      'href' => 'node/' . $entity_id . '/outline/children',
      'localized_options' => array(),
    );
    // duplicate this part
    $links['cis_lmsless_duplicate_outline'] = array(
      'title' => t('Duplicate'),
      'href' => 'node/' . $entity_id . '/outline/copy',
      'localized_options' => array(),
    );
  }
}

/**
 * Implements hook_menu().
 */
function mooc_helper_menu() {
  $items = array();
  // load a page with the active outline's table of contents displayed
  $items['mooc/book-toc'] = array(
    'title' => 'Instructional outline',
    'page callback' => '_mooc_helper_toc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function mooc_helper_block_info() {
  // block that renders the table of contents
  $blocks['mooc_helper_toc'] = array(
    'info' => t('Active outline Table of Contents'),
    'cache' => DRUPAL_NO_CACHE
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function mooc_helper_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'mooc_helper_toc':
      $block['subject'] = t('Table of Contents');
      $block['content'] = _mooc_helper_toc();
    break;
  }
  return $block;
}

/**
 * Callback for mooc/book-toc to deliver the table of contents
 * @return string  rendered table of contents for the active outline.
 */
function _mooc_helper_toc() {
  $tree = array();
  $node = _cis_service_connection_active_outline();
  // exit early cause we found nothing
  if (!$node) {
    return FALSE;
  }
  // load the active outline
  $active = menu_get_object();
  // test for not being on a node as well as global setting overriding
  // outline to use
  if (!isset($active->book) || ($active->book['menu_name'] != $node->book['menu_name'])) {
    $active = $node;
  }
  // only show the block if the user has view access for the top-level node.
  if (entity_access('view', 'node', $active) && isset($active->book)) {
    // load everything the tree below as well as the active trail
    $tree = _mooc_helper_menu_tree_all_data($active->book['menu_name'], $active->book);
    // dump the highest book node, we don't need this "page"
    $tree = array_pop($tree);
    // ensure we only render what's below us
    $tree = $tree['below'];
  }
  return menu_tree_output($tree);
}

/**
 * Fork of menu_tree_all_data.
 * @see  menu_tree_all_data
 */
function _mooc_helper_menu_tree_all_data($menu_name, $link = NULL, $max_depth = NULL) {
  $tree = &drupal_static(__FUNCTION__, array());

  // Use $mlid as a flag for whether the data being loaded is for the whole tree.
  $mlid = isset($link['mlid']) ? $link['mlid'] : 0;
  // Generate a cache ID (cid) specific for this $menu_name, $link, $language, and depth.
  $cid = 'toc:links:' . $menu_name . ':all:' . $mlid . ':' . $GLOBALS['language']->language . ':' . (int) $max_depth;

  if (!isset($tree[$cid])) {
    // If the static variable doesn't have the data, check {cache_menu}.
    $cache = cache_get($cid, 'cache_menu');
    if ($cache && isset($cache->data)) {
      // If the cache entry exists, it contains the parameters for
      // menu_build_tree().
      $tree_parameters = $cache->data;
    }
    // If the tree data was not in the cache, build $tree_parameters.
    if (!isset($tree_parameters)) {
      $tree_parameters = array(
        'min_depth' => 1,
        'max_depth' => $max_depth,
      );
      if ($mlid) {
        // The tree is for a single item, so we need to match the values in its
        // p columns and 0 (the top level) with the plid values of other links.
        $parents = array(0);
        for ($i = 1; $i < MENU_MAX_DEPTH; $i++) {
          if (!empty($link["p$i"])) {
            $parents[] = $link["p$i"];
          }
        }
        $tree_parameters['expanded'] = $parents;
        $tree_parameters['active_trail'] = $parents;
        $tree_parameters['active_trail'][] = $mlid;
      }

      // Cache the tree building parameters using the page-specific cid.
      cache_set($cid, $tree_parameters, 'cache_menu');
    }

    // Build the tree using the parameters; the resulting tree will be cached
    // by _menu_build_tree()).
    unset($tree_parameters['expanded']);
    $tree_parameters['only_active_trail'] = FALSE;
    $tree[$cid] = menu_build_tree($menu_name, $tree_parameters);
  }

  return $tree[$cid];
}

/**
 * Return a list of all book roots as an array
 *
 * @param $property
 *   property to use as the unique key, defaults to uuid.
 * @param $title
 *   (optional) property to use as the title field in array.
 * @return $outlines
 *   an array of outlines keyed as property => title
 */
function _mooc_helper_all_book_outlines($property = 'uuid', $title = '') {
  $outlines = array();
  // load all book outline etids
  foreach (book_get_books() as $book_id => $book) {
    // load book node fully
    $node = node_load($book['nid']);
    if ($title == '') {
      $set_title = $node->book['link_title'];
    }
    else {
      $set_title = $node->{$title};
    }
    // create an array
    $outlines[$node->{$property}] = $set_title;
  }
  return $outlines;
}

/**
 * Implements hook_node_presave().
 */
function mooc_helper_node_presave($node) {
  // make sure there's an outline associated to this
  // but only if we have at least 1 to do so with
  if ($node->type == 'section') {
    // ensure an outline is set, if not use default
    if (empty($node->field_instructional_outlines['und'])) {
      $default = variable_get('mooc_default_outline', '');
      // edge case, default was never set
      if ($default == '') {
        // load all books
        $books = _mooc_helper_all_book_outlines('nid', 'created');
        // make sure we at least have some books in here
        if (is_array($books)) {
          // move to 1st array position in iterator
          reset($books);
          // sort maintaining index which is the nid
          asort($books);
          // set default to first key in array
          $default = key($books);
        }
      }
      // make sure we have something to set
      if ($default != '') {
        $node->field_instructional_outlines['und'][0]['target_id'] = $default;
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function mooc_helper_form_cis_service_connection_ux_form_alter(&$form, &$form_state, $form_id) {
  $form['mooc'] = array(
    '#tree' => '0',
    '#type' => 'fieldset',
    '#collapsed' => '0',
    '#collapsible' => '1',
    '#title' => t('Content settings'),
    '#weight' => '-1',
  );
  $form['mooc']['mooc_default_outline'] = array(
    '#description' => t('This is the default content outline for new sections that register.'),
    '#default_value' => variable_get('mooc_default_outline', ''),
    '#weight' => '0',
    '#title' => t('Default content outline'),
    '#type' => 'select',
    '#required' => '1',
    '#options' => _mooc_helper_all_book_outlines('nid'),
  );
}

/**
 * Implements hook_tokens($type, $tokens, array $data = array(), array $options = array().
 */
function mooc_helper_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();
  // tokens from section
  if ($type == 'elmsln_section') {
    $outline_node = _cis_service_connection_active_outline();
    $section = _cis_connector_section_context();
    foreach ($tokens as $name => $original) {
      // elements we know about ahead of time
      switch ($name) {
        case 'active_outline_nid':
          $replacements[$original] = $outline_node->nid;
          $replacements[$original] = '<span data-cis-token="' . t('Scope: Current section') . '<br/>' . t('Token: @token', array('@token' => strip_tags($original))) . '"  class="cis_token_dynamic_value">' . $replacements[$original] . '</span>';
        break;
      }
    }
  }
  if ($type == 'elmsln_section_data') {
    $outline_node = _cis_service_connection_active_outline();
    $section = _cis_connector_section_context();
    foreach ($tokens as $name => $original) {
      // elements we know about ahead of time
      switch ($name) {
        case 'active_outline_nid':
          if (isset($outline_node->nid)) {
            $replacements[$original] = $outline_node->nid;
          }
        break;
      }
    }
  }

  return $replacements;
}

/**
 * Provide information about our custom tokens.
 *
 * @see http://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_token_info/7
 * @see http://www.benmarshall.me/drupal-custom-tokens
 * @return array
 *   An associative array of available tokens and token types.
 */
function mooc_helper_token_info() {
  // provide feedback about the active outline nid token
  $outline_node = _cis_service_connection_active_outline();
  $outline = 'empty';
  if (isset($outline_node->nid)) {
    $outline = $outline_node->nid;
  }
  $tokens = array(
    'elmsln_section' => array(
      'active_outline_nid' => array(
        'name' => t("Active content outline"),
        'description' => t('Section based token whose value is currently @val, just the value.', array('@val' => $outline)),
      ),
    ),
  );
  // mirror this info for the data section that applies without scope wrappers
  $tokens['elmsln_section_data'] = $tokens['elmsln_section'];

  return array(
    'tokens' => $tokens,
  );
}
