; This file was auto-generated by drush make
core = 7.x

api = 2

; Modules
projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.2"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc5"

projects[admin_views][subdir] = "contrib"
projects[admin_views][version] = "1.3"

projects[atjs][subdir] = "contrib"
projects[atjs][version] = "1.x-dev"

projects[better_exposed_filters][subdir] = "contrib"
projects[better_exposed_filters][version] = "3.0"

projects[better_formats][subdir] = "contrib"
projects[better_formats][version] = "1.0-beta1"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.5"

projects[clamav][subdir] = "contrib"
projects[clamav][version] = "1.0-alpha2"

projects[codefilter][subdir] = "contrib"
projects[codefilter][version] = "1.1"

projects[context][subdir] = "contrib"
projects[context][version] = "3.5"

projects[date][subdir] = "contrib"
projects[date][version] = "2.8"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[elements][subdir] = "contrib"
projects[elements][version] = "1.4"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

projects[entity_quote][subdir] = "contrib"
projects[entity_quote][version] = "1.x-dev"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1"

projects[entityreference_prepopulate][subdir] = "contrib"
projects[entityreference_prepopulate][version] = "1.5"

projects[features][subdir] = "contrib"
projects[features][version] = "2.2"

projects[features_override][subdir] = "contrib"
projects[features_override][version] = "2.0-rc2"

projects[flag][subdir] = "contrib"
projects[flag][version] = "3.5"

projects[harmony_core][subdir] = "contrib"
projects[harmony_core][version] = "1.x-dev"

projects[harmony_moderation][subdir] = "contrib"
projects[harmony_moderation][version] = "1.x-dev"

projects[honeypot][subdir] = "contrib"
projects[honeypot][version] = "1.17"

projects[inline_entity_form][subdir] = "contrib"
projects[inline_entity_form][version] = "1.5"

projects[jquery_colorpicker][subdir] = "contrib"
projects[jquery_colorpicker][version] = "1.1"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.4"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[machine_name][subdir] = "contrib"
projects[machine_name][version] = "1.0"

projects[markdown][subdir] = "contrib"
projects[markdown][version] = "1.2"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[placeholder][subdir] = "contrib"
projects[placeholder][version] = "1.1"

projects[readmorejs][subdir] = "contrib"
projects[readmorejs][version] = "1.0"

projects[short_scale_formatter][subdir] = "contrib"
projects[short_scale_formatter][version] = "1.1"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[taxonomy_display][subdir] = "contrib"
projects[taxonomy_display][version] = "1.1"

projects[timeago][subdir] = "contrib"
projects[timeago][version] = "2.3"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[transliteration][subdir] = "contrib"
projects[transliteration][version] = "3.2"

projects[viewfield][subdir] = "contrib"
projects[viewfield][version] = "2.0"

projects[views][subdir] = "contrib"
projects[views][version] = "3.8"

projects[views_flag_refresh][subdir] = "contrib"
projects[views_flag_refresh][version] = "1.3"

projects[views_load_more][subdir] = "contrib"
projects[views_load_more][version] = "1.5"

projects[wysiwyg_filter][subdir] = "contrib"
projects[wysiwyg_filter][version] = "1.6-rc2"

; Themes
projects[bootstrap][version] = "3.0"

projects[harmony_install_theme][version] = "1.x-dev"

; Modules

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[at.js][download][type] = "get"
libraries[at.js][download][url] = "https://github.com/ichord/At.js/archive/v0.5.2.tar.gz"
libraries[at.js][directory_name] = "at.js"
libraries[at.js][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[caret.js][download][type] = "get"
libraries[caret.js][download][url] = "https://github.com/ichord/Caret.js/archive/v0.2.1.tar.gz"
libraries[caret.js][directory_name] = "caret.js"
libraries[caret.js][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorpicker][download][type] = "get"
libraries[colorpicker][download][url] = "http://www.eyecon.ro/colorpicker/colorpicker.zip"
libraries[colorpicker][directory_name] = "colorpicker"
libraries[colorpicker][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[placeholder][download][type] = "get"
libraries[placeholder][download][url] = "https://github.com/mathiasbynens/jquery-placeholder/archive/v2.0.8.tar.gz"
libraries[placeholder][directory_name] = "placeholder"
libraries[placeholder][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[readmore.js][download][type] = "git"
libraries[readmore.js][download][url] = "https://github.com/jedfoster/Readmore.js.git"
libraries[readmore.js][directory_name] = "readmore.js"
libraries[readmore.js][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[timeago][download][type] = "get"
libraries[timeago][download][url] = "http://timeago.yarp.com/jquery.timeago.js"
libraries[timeago][directory_name] = "timeago"
libraries[timeago][type] = "library"
