<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_wysiwyg_templates_load_alter().
 */
function textbook_templates_wysiwyg_templates_load_alter(&$templates) {
  // This is the array we need to add stuff to...
  $textbook = array(
    'grid_of_video',
    'buttons',
    'case_study',
    'callout_panel',
    'regular_panel',
    'two_column_list_image',
    'two_column_list_video',
    'topic_reading',
    'quote',
    'flex_video',
    'lorem_ipsum',
    'clean_table',
    'table_of_terms',
    'table_style_1',
    'table_style_2',
    'magellan_navigation'
  );
  foreach ($templates as $key => $template) {
    // see if the template matches one in the textbook definition
    if ($template['image'] == '' && in_array($template['name'], $textbook) === TRUE) {
      $templates[$key]['image'] = '/' . drupal_get_path('module', 'textbook_templates') . '/images/' . $template['name'] . '.png';
    }
  }
}