#!/bin/bash
# you should be able to copy and paste these 3 lines into a bash
# prompt and effectively install and completely optimize elmsln
# on a new machine that has just been created
# no dependencies to worry about, just take the red pill and copy
# and paste on a fresh server.
# The 3rd line you'll want to fill out with your own values if you
# are spinning this up to actually run somewhere, but the example input
# will work to give you a taste of what its about to do when your ready for
# the real deal to be deployed somewhere.
yes | yum -y install git
git clone https://github.com/btopro/elmsln.git /var/www/elmsln
bash /var/www/elmsln/scripts/install/handsfree/centos/centos-install.sh elmsln ln elmsln.dev http email@elmsln.dev yes

# for dev usage:
# look to the elmsln vagrant for instructions on how to remap your /etc/hosts
# https://github.com/btopro/elmsln-vagrant#how-to-use-this-to-bring-up-elmsln
# then change the .local to .dev and change the ip address to your server IP
# use the following to figure this out:
#
# ifconfig | grep 'inet addr'


# for production usage:
# describing the values a bit more; all of these are machine_name input
# elmsln: college/university deployment
# ln: 2 letter to represent organizational unit
# elmsln.dev: domain to use as the base for the network
# http: protocol; http or https for all communications
# email@elmsln.dev: admin email address
# yes: report to our anonymous analytics program when we start it yes/no
