#!/bin/bash
# you should be able to copy and paste these 3 lines into a bash
# prompt and effectively install and completely optimize elmsln
# on a new machine that has just been created
# no dependencies to worry about, just take the red pill and copy
# and paste on a fresh server.
# The 3rd line you'll want to fill out with your own values if you
# are spinning this up to actually run somewhere, but the example input
# will work to give you a taste of what its about to do when your ready for
# the real deal to be deployed somewhere.
yes | yum -y install git
git clone https://github.com/btopro/elmsln.git /var/www/elmsln
bash /var/www/elmsln/scripts/install/handsfree/centos/centos-install.sh college ln example.com http email@example.com yes

# describing the values a bit more; all of these are machine_name input
# college/university deployment
# 2 letter to represent organizational unit
# domain to use as the base for the network
# protocol; http or https for all communications
# admin email address
# report to our anonymous analytics program when we start it yes/no
