<?php
/**
 * @file
 * Code for the CLE Project feature.
 */

include_once 'cle_project.features.inc';

/**
 * Implements hook_menu().
 */
function cle_project_menu() {
  $items = array();
  $items['api/v1/cle/projects'] = array(
    'page callback' => '_elmsln_api_v1_page_callback',
    'page arguments' => array('project'),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
  );
  $items['api/v1/cle/projects/create'] = array(
    'page callback' => '_elmsln_api_v1_page_callback',
    'page arguments' => array('project', 4),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
  );
  $items['api/v1/cle/projects/fields'] = array(
    'page callback' => '_elmsln_api_v1_page_callback',
    'page arguments' => array('project', 4),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
  );
  $items['api/v1/cle/projects/%'] = array(
    'page callback' => '_elmsln_api_v1_page_callback',
    'page arguments' => array('project', 4),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_elmsln_jsapi_info().
 */
function cle_project_elmsln_jsapi_info() {
  // assignment api router
  $items['project'] = array(
    'type' =>   'cle_project',
    'create' => '_cle_project_v1_project_create',
    'list' =>   '_cle_project_v1_get_projects',
    'output' => '_cle_project_v1_project_output',
  );
  return $items;
}

/**
 * @todo
 * Get all of the projects for the current user
 * - Make sure that they are seeing projects for their current section
 */
function _cle_project_v1_get_projects($filter = array()) {
  $items = array();
  $field_conditions = array();
  $property_conditions = array('status' => array(NODE_PUBLISHED, '='));
  if (isset($filter['project'])) {
    $property_conditions['nid'] = array($filter['project'], '=');
  }
  $orderby = array();
  $items = _cis_connector_assemble_entity_list('node', 'cle_project', 'nid', '_entity', $field_conditions, $property_conditions, $orderby);
  return $items;
}

/**
 * Helper function that prepares a submission for api output.
 */
function _cle_project_v1_project_output($node) {
  global $base_url;
  // this will be our json formatted output
  $return = array(
    'id' => (int)$node->nid,
    'title' => $node->title,
    'status' => (int)$node->status,
    'created' => (int)$node->created,
    'body' => $node->field_project_description[LANGUAGE_NONE][0]['safe_value'],
    'links' => array(
      'self' => $base_url . '/api/v1/cle/projects/' . $node->nid,
    ),
  );
  return $return;
}

/**
 * ELMSLN JSapi callback for creating an assignment.
 * @todo  make this use the full POST data sanitized and in params.
 */
function _cle_project_v1_project_create($type, $params = NULL) {
  $node = _elmsln_api_stub_node($type);
  foreach ($params as $key => $value) {
    // fields we support in a POST
    switch ($key) {
      case 'uid':
      case 'title':
        $node->{$key} = $value;
      break;
    }
  }
  node_save($node);
  // output the newly created assignment
  $vars = array(
    'status' => '200',
    'detail' => 'Project created',
    'assignment' => (array) $node,
  );
  return $vars;
}
