<?php
/**
 * @file
 * Installation, updates, and requirements for FastClick module
 */


/**
 * Disables FastClick Everywhere module now that its code has been integrated
 * into the FastClick module. Note that now FastClick module attaches the
 * library on every page by default. See README.txt and module file for
 * more details.
 */
function fastclick_update_7001() {
  module_disable(array('fastclick_everywhere'), FALSE);
}
