#!/bin/bash
#where am i? move to where I am. This ensures source is properly sourced
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

source ../../config/scripts/drush-create-site/config.cfg

txtbld=$(tput bold)             # Bold
bldgrn=${txtbld}$(tput setaf 2) #  green
bldred=${txtbld}$(tput setaf 1) #  green
txtreset=$(tput sgr0)
elmslnecho(){
  echo "${bldgrn}$1${txtreset}"
  return 1
}
elmslnwarn(){
  echo "${bldred}$1${txtreset}"
  return 1
}

#test for empty vars. if empty required var -- exit
if [ -z $elmsln ]; then
  elmslnwarn "please update your config.cfg file"
  exit 1
fi
if [ -z $host ]; then
  elmslnwarn "please update your config.cfg file"
  exit 1
fi

elmslnecho "Are you sure you want to upgrade the entire network? (Type yes)"
read yesprompt
if [ "$yesprompt" != "yes" ]; then
  elmslnwarn "please type yes to execute the script, exited early"
  exit 1
fi

#prevent the script from being run more than once
if [ -f /tmp/elmsln-upgrade-lock ]; then
  elmslnwarn 'elmsln-upgrade-lock is in place, this command must have failed previously or is currently already running.'
  elmslnwarn "in order to override this manually you'll have to run rm /tmp/elmsln-upgrade-lock"
  exit 1
fi
touch /tmp/elmsln-upgrade-lock

# issue the git pull to master
#cd ../..
#git pull origin master

# stacks we currently only care about as stand alone
standalone=('online')
for stack in "${standalone[@]}"
do
  elmslnecho "working against $stack"
  # alias to take each site offline
  elmslnecho "$stack: sites currently offline to avoid write issues"
  drush @${stack}-all offline --y
  elmslnecho "$stack: rebuilding registry to avoid file location issues"
  drush @${stack}-all rr --y
  elmslnecho "$stack: running potential database updates"
  drush @${stack}-all updb --y
  elmslnecho "$stack: execute cron"
  drush @${stack}-all cron --y
  elmslnecho "$stack: clearing caches, though previous should have but to be safe"
  drush @${stack}-all cc all --y
  elmslnecho "$stack: seed entity cache"
  drush @${stack}-all hss --y
  # alias to bring them all back online
  elmslnecho "$stack: sites should be back online"
  drush @${stack}-all online --y
done

# stacks we currently support spidering against individual networks
masterstacklist=('studio' 'interact' 'blog' 'media')
stackdir=$elmsln/core/dslmcode/stacks
empty=""
primarystack='courses'

if [ -d $stackdir/$primarystack/sites/$primarystack/$host ];
then
  fullpath=$stackdir/$primarystack/sites/$primarystack/$host
  coursemachinename=""
  # do a find in this directory
  for course in $stackdir/$primarystack/sites/$primarystack/$host/*/settings.php ;
  do
    # drop /settings.php from the path and split based on / for directories
    IFS='/' read -ra folder <<< "${course/\/settings.php/$empty}"
    for foldername in "${folder[@]}"; do
      # the last one is gaurenteed to be the course!
      coursemachinename=$foldername
    done
    # make sure we found a course
    if [ "$coursemachinename" != "$empty" ]; then
      elmslnecho "${bldgrn}$coursemachinename: working against course network ${txtreset}"
      # networks can be custom, lets see what tools this one uses
      stacklist=($primarystack)
      for stack in "${masterstacklist[@]}"
      do
        # if we found a settings.php here then we know we have a valid service
        if [ -f $stackdir/$stack/sites/$stack/$host/$coursemachinename/settings.php ]; then
          stacklist=("${stacklist[@]}" "$stack")
        fi
      done
      elmslnecho "$coursemachinename: take network offline to avoid write issues"
      for stack in "${stacklist[@]}"
      do
        # alias to take each site offline
        elmslnecho "${stack}"
        drush @${stack}.${coursemachinename} offline --y
      done
      elmslnecho "$coursemachinename: rebuilding registry to avoid file location issues"
      for stack in "${stacklist[@]}"
      do
        elmslnecho "${stack}"
        drush @${stack}.${coursemachinename} rr --y
      done
      elmslnecho "$coursemachinename: running potential database updates"
      for stack in "${stacklist[@]}"
      do
        elmslnecho "${stack}"
        drush @${stack}.${coursemachinename} updb --y
      done
      elmslnecho "$coursemachinename: executing cron"
      for stack in "${stacklist[@]}"
      do
        elmslnecho "${stack}"
        drush @${stack}.${coursemachinename} cron --y
      done
      elmslnecho "$coursemachinename: clearing caches"
      for stack in "${stacklist[@]}"
      do
        elmslnecho "${stack}"
        drush @${stack}.${coursemachinename} cc all --y
      done
      elmslnecho "$coursemachinename:$stack seed caches"
      for stack in "${stacklist[@]}"
      do
        elmslnecho "${stack}"
        drush @${stack}.${coursemachinename} ecl --y
      done
      elmslnecho "$coursemachinename: bring network back online"
      for stack in "${stacklist[@]}"
      do
        # alias to bring site back online
        elmslnecho "${stack}"
        drush @${stack}.${coursemachinename} online --y
      done
      elmslnecho "$coursemachinename network upgrade complete"
    fi
  done
  elmslnecho "ELMSLN network wide upgrade complete"
fi

rm /tmp/elmsln-upgrade-lock
