<?php

use Drupal\testmod_psr4_custom\Foo;
use Drupal\xautoload\Tests\Util\StaticCallLog;

xautoload()->main->registerModulePsr4(__FILE__, 'psr4');

function testmod_psr4_custom_init() {
  StaticCallLog::addCall();
  new Foo;
}

function testmod_psr4_custom_modules_enabled() {
  StaticCallLog::addCall();
  new Foo;
}

function testmod_psr4_custom_watchdog() {
  StaticCallLog::addCall();
  new Foo;
}
