<?php

/**
 * @file
 * Generate a EPUB for the print_epub module using the PHPePub library.
 *
 * @ingroup print
 */

/**
 * Find out the version of the PHPePub library.
 *
 * @param string $epub_tool
 *   Filename of the tool to be analysed.
 *
 * @return string
 *   version number of the library
 */
function _print_epub_phpepub_version($epub_tool) {
  require_once DRUPAL_ROOT . '/' . $epub_tool;

  return EPub::VERSION;
}

/**
 * Implements hook_print_epub_available_libs_alter().
 */
function print_epub_phpepub_print_epub_available_libs_alter(&$epub_tools) {
  module_load_include('inc', 'print', 'includes/print');
  $tools = _print_scan_libs('phpepub', '!^EPub.php$!');

  foreach ($tools as $tool) {
    $epub_tools['print_epub_phpepub|' . $tool] = 'PHPePub (' . dirname($tool) . ')';
  }
}
