#!/bin/bash
#where am i? move to where I am. This ensures source is properly sourced
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

#use the same settings as the create site
source ../../config/scripts/drush-create-site/config.cfg
commandloc=$fileloc/drush-command-job

#test for empty vars. if empty required var -- exit
if [ -z $fileloc ]; then
  echo "please update your config.cfg file"
  exit 1
fi
if [ -z $webdir ]; then
  echo "please update your config.cfg file"
  exit 1
fi

date=`date +%Y-%m-%d_%H:%M:%S`

#prevent the script from being run more than once
if [ -f /tmp/drush-command-lock ]; then
  exit 1
fi
touch /tmp/drush-command-lock

#read the files in the $commandloc and set vars based on file name.
for jobfile in `find $commandloc -maxdepth 1 ! -name *.swp ! -name '*processing*' ! -name '*error' ! -name '*processed' ! -name '*example' ! -name '*.md' -type f`
do
  #start processing
  /bin/mv $jobfile $jobfile.processing
  #this will be made up of drush calls
  #@todo do more then just this as far as error checking is concerned
  bash $jobfile.processing
  # move this to processed state after its finished
  if [[ -f  $coursefile.processing ]]; then
    mv $coursefile.processing $coursefile.processed
  fi
done
rm /tmp/drush-command-lock
