<?php
/*******************************************************************************
 * Drupal Hooks */
/**
 * Implements hook_filter_info().
 */
function lazyloader_filter_filter_info() {
  $filters['lazyloader_filter'] = array(
    'title' => t('Lazyloader Filter'),
    'description' => t('Converts &lt;img&gt; tags to load via lazyloader. Automatically applied when enabled as a text filter.'),
    'process callback' => '_lazyloader_filter_filter_process',
  );
  return $filters;
}

/**
 * Implements hook_theme()
 */
function lazyloader_filter_theme($existing, $type, $theme, $path) {
  return array(
    'lazyloader_filter_image' => array(
      'variables' => array('attr' => NULL, 'attr_str' => NULL),
      'template' => 'lazyloader-filter-image',
    ));
}

/**
 * Implements hook_form_FORM_ID_alter() -> lazyloader_admin
 */
function lazyloader_filter_form_lazyloader_admin_alter(&$form, &$form_state) {
  $form['#submit'][] = '_lazyloader_filter_admin_submit';
}

/*******************************************************************************
 * Helper functions */
/**
 * Replace <img> tags with lazy loading images
 */
function _lazyloader_filter_filter_process($text) {
  // current lazyloader settings
  $settings = variable_get('lazyloader');

  // if lazyloading is enabled, use lazy loading
  if ($settings['enabled']) return preg_replace_callback('/<img\b[^>]*>/', '_lazyloader_filter_process_matches', $text);

  // not using lazy loading
  return $text;
}

/**
 * Process the image tags found with preg_replace_callback().
 * Addapted from aamonkey's solution posted at http://www.sitepoint.com/forums/showthread.php?361137-Regular-expression-to-get-img-attributes&s=ec165cc8c55543bfd8820c20ba1d6b9c&p=2602886&viewfull=1#post2602886
 */
function _lazyloader_filter_process_matches($matches) {
  // Extract attributes from each img tag and place in $attributes array.
  // $attributes_string is a string of all attributes EXCEPT src (passed to template for easy theming).
  $attributes = array();
  $attributes_string = '';
  foreach ($matches as $m) {
    preg_match_all("#(\w+)=['\"]{1}([^'\"]*)#", $m, $matches2);
    foreach($matches2[1] as $key => $val) {
      $attributes[$val] = $matches2[2][$key];
      if ($val != 'src') {
        $attributes_string .= $val . '="' . $matches2[2][$key] . '" ';
      }
    }
  }

  // Return the themed image
  return theme('lazyloader_filter_image', array('attr' => $attributes, 'attr_str' => $attributes_string));
}

/**
 * Additional submit handler for the lazyload admin form
 */
function _lazyloader_filter_admin_submit($form, $form_state) {
  // we need to flush the field cache if things change
  if ($form['lazyloader']['enabled']['#default_value'] != $form['lazyloader']['enabled']['#value']) {
    cache_clear_all('*', 'cache_field', TRUE);
  }
}
