; This file was auto-generated by drush make
core = 7.23

api = 2

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.4"

projects[features][subdir] = "contrib"
projects[features][version] = "2.0"

projects[markdown][subdir] = "contrib"
projects[markdown][version] = "1.2"

projects[meedjum_base][subdir] = "features"
projects[meedjum_base][version] = "1.0-alpha2"

projects[references][subdir] = "contrib"
projects[references][version] = "2.1"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"

; Themes
projects[meedjum][version] = "1.0-alpha1"

