#!/bin/bash
# you should be able to copy and paste these 3 lines into a bash
# prompt and effectively install and completely optimize elmsln
# on a new machine that has just been created
# no dependencies to worry about, just take the red pill and copy
# and paste on a fresh server.
# The 3rd line you'll want to fill out with your own values if you
# are spinning this up to actually run somewhere, but the example input
# will work to give you a taste of what its about to do when your ready for
# the real deal to be deployed somewhere.
apt-get update && apt-get -y install wget git && git clone https://github.com/elmsln/elmsln.git /var/www/elmsln && bash /var/www/elmsln/scripts/install/handsfree/ubuntu/ubuntu-install.sh elmsln ln elmsln.dev http email@elmsln.dev yes
cd $HOME && source .bashrc

# for production usage:
# describing the values a bit more; all of these are machine_name input
# elmsln: college/university deployment
# ln: 2 letter to represent organizational unit
# elmsln.dev: domain to use as the base for the network
# http: protocol; http or https for all communications
# email@elmsln.dev: admin email address
# yes: report to our anonymous analytics program when we start it yes/no
