<?php

/**
 * @file
 * 
 * Main module file for Views Simple Pager, contains core Drupal hook implementations
 */

/**
 * Implements hook_views_api().
 */
function views_simple_pager_views_api() {
  return array('api' => '3.0');
}

/**
 * Implements hook_theme().
 */
function views_simple_pager_theme($existing, $type, $theme, $path) {
  $path = drupal_get_path('module', 'views_simple_pager');

  // Our extra version of pager from pager.inc
  $items['views_simple_pager'] = array(
    'file' => 'views_simple_pager.theme.inc',
    'variables' => array('tags' => array(), 'element' => 0, 'parameters' => array(), 'options' => array()),
    'pattern' => 'views_simple_pager__',
  );
  
  return $items;
}
