<?php
/**
 * @file
 * Code for CPR helper.
 */


/**
 * Implements hook_cron().
 */
function cpr_helper_cron() {
  // load up courses as we'll have all of them locally
  $courses = _cis_connector_assemble_entity_list('node', 'cis_course', 'field_course_machine_name', 'nid');
  // loop through each course and query to sync the section rosters
  foreach ($courses as $machine_name => $nid) {
    _cis_section_sync_roster($machine_name, $nid);
  }
}