<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_entity_info_alter().
 */
function foundation_access_viewmodes_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['image'] = array(
    'label' => t('Image'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['image__left'] = array(
    'label' => t('Image Left'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['image__right'] = array(
    'label' => t('Image Right'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['image__boxed'] = array(
    'label' => t('Image Boxed'),
    'custom settings' => FALSE,
  );
}