<?php

/**
 * @file
 * Implementation of Entity Assessment Entity.
 */

/**
 * Implements hook_entity_info().
 */
function assessment_entity_entity_info() {
  $return['assessment_entity'] = array(
    'label' => t('Assessment Entity'),
    // The entity class and controller class extend the default entity classes.
    'entity class' => 'AssessmentEntity',
    'controller class' => 'AssessmentEntityController',
    'base table' => 'assessment_entity',
    'fieldable' => TRUE,
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'assessment_entity_id',
      'bundle' => 'type',
    ),
    // Bundles are defined by the types below.
    'bundles' => array(),
    'bundle keys' => array('bundle' => 'type'),
    'label callback' => 'entity_class_label',
    'uri callback' => 'entity_class_uri',
    'access callback' => 'assessment_entity_access',
    'module' => 'assessment_entity',
    // The information below is used by the Controller;
    // which extends the EntityDefaultUIController.
    'admin ui' => array(
      'path' => 'admin/content/assessment_entity',
      'file' => 'includes/assessment_entity.admin.inc',
      'controller class' => 'AssessmentEntityUIController',
      'menu wildcard' => '%assessment_entity',
    ),
  );
  // The entity that holds information about the entity types.
  $return['assessment_entity_type'] = array(
    'label' => t('Assessment Entity Type'),
    'entity class' => 'AssessmentEntityType',
    'controller class' => 'AssessmentEntityTypeController',
    'base table' => 'assessment_entity_type',
    'fieldable' => FALSE,
    'bundle of' => 'assessment_entity',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'type',
      'label' => 'label',
    ),
    'access callback' => 'assessment_entity_type_access',
    'module' => 'assessment_entity',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/structure/assessment_entity_types',
      'file' => 'includes/assessment_entity_type.admin.inc',
      'controller class' => 'AssessmentEntityTypeUIController',
    ),
  );

  return $return;
}

/**
 * Implements hook_entity_info_alter().
 */
function assessment_entity_entity_info_alter(&$entity_info) {
  foreach (assessment_entity_get_types() as $type => $info) {
    $entity_info['assessment_entity']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/structure/assessment_entity_types/manage/%assessment_entity_type',
        'real path' => 'admin/structure/assessment_entity_types/manage/' . $type,
        'bundle argument' => 4,
        'access arguments' => array('administer Assessment Entity types'),
      ),
    );
  }
}

/**
 * Implements hook_permission().
 */
function assessment_entity_permission() {
  // We set up permisssions to manage entity types, manage all entities and the
  // permissions for each individual entity.
  $permissions = array(
    'administer Assessment Entity types' => array(
      'title' => t('Administer Assessment Entity types'),
      'description' => t('Create and delete fields for Assessment Entity types, and set their permissions.'),
    ),
    'administer Assessment Entity' => array(
      'title' => t('Administer Assessment Entity'),
      'description' => t('Edit and delete all Assessment Entity'),
    ),
  );

  // Generate permissions.
  foreach (assessment_entity_get_types() as $type) {
    $type_name = check_plain($type->type);
    $permissions += array(
      "edit any $type_name Assessment Entity" => array(
        'title' => t('%type_name: Edit any Assessment Entity', array('%type_name' => $type->label)),
      ),
      "view any $type_name Assessment Entity" => array(
        'title' => t('%type_name: View any Assessment Entity', array('%type_name' => $type->label)),
      ),
    );
  }

  return $permissions;
}

/**
 * Implements hook_theme().
 */
function assessment_entity_theme() {
  return array(
    'assessment_entity' => array(
      'render element' => 'elements',
      'template' => 'assessment_entity',
    ),
  );
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function assessment_entity_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link 'admin/structure/assessment_entity/add'
  // on 'admin/structure/assessment_entity'.
  if ($root_path == 'admin/content/assessment_entity') {
    $item = menu_get_item('admin/content/assessment_entity/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Determines whether the given user has access to a Assessment Entity.
 *
 * @param string $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 *
 * @param object $entity
 *   Optionally a Assessment Entity or a Assessment Entity type to check access for.
 *   If nothing is given, access for all Assessment Entity is determined.
 *
 * @param object $account
 *   The user to check for. Leave it to NULL to check for the global user.
 *
 * @return bool
 *   Whether access is allowed or not.
 */
function assessment_entity_access($op, $entity = NULL, $account = NULL) {
  if (user_access('administer Assessment Entity', $account)) {
    return TRUE;
  }

  if (isset($entity) && $type_name = $entity->type) {
    $op = ($op == 'view') ? 'view' : 'edit';
    if (user_access("$op any $type_name Assessment Entity", $account)) {
      return TRUE;
    }
  }

  return FALSE;
}

/**
 * Access callback for the entity API.
 */
function assessment_entity_type_access($op, $type = NULL, $account = NULL) {
  return user_access('administer Assessment Entity types', $account);
}

/**
 * Gets an array of all Assessment Entity types, keyed by the type name.
 *
 * @param string $type_name
 *   If set, the type with the given name is returned.
 *
 * @return array
 *   Depending whether $type isset, an array of Assessment Entity types
 *   or a single one.
 */
function assessment_entity_get_types($type_name = NULL) {
  // entity_load will get the Entity controller for our Assessment Entity entity
  // and call the load function of that object.
  // We are loading entities by name here.
  $types = entity_load_multiple_by_name('assessment_entity_type', isset($type_name) ? array($type_name) : FALSE);

  return isset($type_name) ? reset($types) : $types;
}

/**
 * Menu argument loader; Load a Assessment Entity type by string.
 *
 * @param string $type
 *   The machine-readable name of a Assessment Entity type to load.
 *
 * @return mixed
 *   A Assessment Entity type array or FALSE if $type does not exist.
 */
function assessment_entity_type_load($type) {
  return assessment_entity_get_types($type);
}

/**
 * Fetch a Assessment Entity object.
 *
 * @param int $assessment_entity_id
 *   Integer specifying the assessment_entity id.
 *
 * @return object
 *   A fully-loaded object or FALSE if it cannot be loaded.
 *
 * @see entity_load_single()
 */
function assessment_entity_load($assessment_entity_id) {
  return entity_load_single('assessment_entity', $assessment_entity_id);
}

/**
 * Load multiple Assessment Entity based on certain conditions.
 *
 * @param array $assessment_entity_ids
 *   An array of Assessment Entity IDs.
 *
 * @param array $conditions
 *   An array of conditions to match against the assessment_entity table.
 *
 * @param bool $reset
 *   A boolean indicating that the internal cache should be reset.
 *
 * @return array
 *   An array of objects, indexed by assessment_entity_id.
 *
 * @see entity_load()
 * @see assessment_entity_load()
 */
function assessment_entity_load_multiple($assessment_entity_ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('assessment_entity', $assessment_entity_ids, $conditions, $reset);
}

/**
 * Deletes a Assessment Entity.
 */
function assessment_entity_delete(AssessmentEntity $assessment_entity) {
  $assessment_entity->delete();
}

/**
 * Delete multiple Assessment Entity.
 *
 * @param array $assessment_entity_ids
 *   An array of Assessment Entity IDs.
 */
function assessment_entity_delete_multiple(array $assessment_entity_ids) {
  return entity_delete_multiple('assessment_entity', $assessment_entity_ids);
}

/**
 * Create a Assessment Entity object.
 */
function assessment_entity_create($values = array()) {
  return entity_create('assessment_entity', $values);
}

/**
 * Saves a Assessment Entity to the database.
 *
 * @param string $assessment_entity
 *   The Assessment Entity object.
 */
function assessment_entity_save($assessment_entity) {
  return entity_save('assessment_entity', $assessment_entity);
}

/**
 * Saves a Assessment Entity type to the db.
 */
function assessment_entity_type_save($type) {
  return entity_save('assessment_entity_type', $type);
}

/**
 * Deletes a Assessment Entity type from the db.
 */
function assessment_entity_type_delete(AssessmentEntityType $type) {
  $type->delete();
}

/**
 * Menu title callback for showing individual entities.
 */
function assessment_entity_page_title(AssessmentEntity $assessment_entity) {
  return $assessment_entity->label;
}

/**
 * Sets up content to show an individual Assessment Entity.
 */
function assessment_entity_page_view($assessment_entity, $view_mode = 'full') {
  return entity_view('assessment_entity_type', array($assessment_entity), $view_mode);
}
