<?php
/**
 * @file
 * Code for the CLE Assignment feature.
 */
// default assignment color for new ones
define('CLE_ASSIGNMENT_DEFAULT_COLOR', 'aac');

include_once 'cle_assignment.features.inc';

/**
 * Implements hook_init().
 */
function cle_assignment_init() {
  if (arg(0) == 'node' && arg(2) == 'assignment_bulk') {
    $file = 'assignment_bulk';
    $path = drupal_get_path('module', 'cle_assignment') . '/';
    drupal_add_js($path . 'js/' . $file . '.js');
    drupal_add_css($path . 'css/' . $file . '.css');
  }
}

/**
 * Implements hook_page_build().
 */
function cle_assignment_page_build(&$page) {
  $node = menu_get_object();
  if ($node && $node->type == 'cle_assignment') {
    $field_conditions = array('field_assignment' => array('target_id', array($node->nid), 'IN'));
    $submission = _cis_connector_assemble_entity_list('node', 'cle_submission', 'nid', 'title', $field_conditions, array('uid' => $GLOBALS['user']->uid));
    $output = '';
    foreach ($submission as $nid => $title) {
      $output .= l($title, 'node/' . $nid) . ' ';
    }
    if (empty($output)) {
      $output = l(t('Submit assignment'),'node/add/cle-submission', array('query' => array('field_assignment' => $node->nid)));
    }
    $page['content']['assignment_submission'] = array(
      '#markup' => $output,
      '#weight' => 100,
    );
  }
}
